"use client";
import { useMemo, useState } from "react";
import { MARKETPLACE_FEES, MARKETPLACE_ORDER } from "@/data/marketplaceFees";
import { calculateProfit, findTargetPrice, type MarketplaceId } from "@/lib/profitability";
const rupiah=(v:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(v);
export function ProfitabilityCalculator(){
 const [cost,setCost]=useState(100000),[price,setPrice]=useState(150000),[quantity,setQuantity]=useState(1),[packaging,setPackaging]=useState(3000),[ads,setAds]=useState(0),[target,setTarget]=useState(20);
 const [rates,setRates]=useState<Record<MarketplaceId,number>>({shopee:0,tiktok:0,tokopedia:0,lazada:0,blibli:0,website:0});
 const rows=useMemo(()=>MARKETPLACE_ORDER.map(id=>{const platform=MARKETPLACE_FEES[id];const fees=rates[id]>0?[{label:"Effective seller fee",rate:rates[id]/100}]:platform.fees;const input={hpp:cost,sellingPrice:price,quantity,packaging,advertising:ads};const result=calculateProfit(input,fees);const targetPrice=findTargetPrice({hpp:cost,quantity,packaging,advertising:ads},fees,target/100);return{platform,result,targetPrice}}).sort((a,b)=>b.result.netProfit-a.result.netProfit),[cost,price,quantity,packaging,ads,target,rates]);
 return <section className="mt-10" id="profit-calculator"><div className="mb-5"><p className="text-xs font-medium uppercase tracking-[0.14em] text-[var(--text-muted)]">Marketplace Profit Calculator</p><h2 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">Hitung profit sebelum listing.</h2><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Masukkan economics produk sekali. Isi effective seller fee dari Seller Center kategori tokomu untuk hasil yang akurat.</p></div><div className="grid gap-4 lg:grid-cols-[minmax(0,360px)_minmax(0,1fr)]"><div className="card h-fit p-4 sm:p-5"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-1"><Money label="HPP / Cost of Goods" value={cost} set={setCost}/><Money label="Harga jual" value={price} set={setPrice}/><Num label="Quantity" value={quantity} set={v=>setQuantity(Math.max(1,v))}/><Money label="Packaging / order" value={packaging} set={setPackaging}/><Money label="Ads / CAC per order" value={ads} set={setAds}/><Num label="Target net margin (%)" value={target} set={setTarget}/></div><div className="mt-5 border-t border-[var(--border)] pt-4"><p className="mb-3 text-xs font-medium">Effective seller fee (%)</p><div className="grid grid-cols-2 gap-2">{MARKETPLACE_ORDER.map(id=><Num key={id} label={MARKETPLACE_FEES[id].label} value={rates[id]} set={v=>setRates(c=>({...c,[id]:Math.max(0,v)}))}/>)}</div></div></div><div className="min-w-0 space-y-3">{rows.map(({platform,result,targetPrice},i)=><article key={platform.id} className="card overflow-hidden p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-[var(--surface-3)] text-xs font-bold">{platform.label[0]}</span><h3 className="text-sm font-semibold">{platform.label}</h3>{i===0?<span className="rounded-full bg-[var(--accent-soft)] px-2 py-0.5 text-[10px]">Best profit</span>:null}</div><p className="mt-2 text-[11px] text-[var(--text-muted)]">{platform.note}</p></div><div className="shrink-0 text-right"><p className="text-[10px] uppercase tracking-wide text-[var(--text-muted)]">Net profit</p><p className={`mt-1 text-base font-semibold sm:text-lg ${result.netProfit>=0?"text-[var(--good)]":"text-red-400"}`}>{rupiah(result.netProfit)}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Platform fee" value={rupiah(result.marketplaceFees)}/><Metric label="Settlement" value={rupiah(result.netSettlement)}/><Metric label="Net margin" value={`${result.netMargin.toFixed(1)}%`}/><Metric label={`Target ${target}%`} value={rupiah(targetPrice)}/></div></article>)}</div></div><p className="mt-4 text-[11px] leading-relaxed text-[var(--text-muted)]">Fee berbeda menurut kategori, seller tier dan program. Nilai yang belum diverifikasi tidak di-hard-code; gunakan effective fee aktual dari Seller Center.</p></section>;
}
function Money({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label className="min-w-0 text-xs text-[var(--text-secondary)]">{label}<div className="relative mt-1.5"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs text-[var(--text-muted)]">Rp</span><input className="w-full min-w-0 rounded-xl border border-[var(--border)] bg-[var(--surface-2)] py-3 pl-9 pr-3 text-base outline-none" inputMode="numeric" type="number" min={0} value={value} onChange={e=>set(Math.max(0,Number(e.target.value)))}/></div></label>}
function Num({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label className="min-w-0 text-[11px] text-[var(--text-secondary)]">{label}<input className="mt-1.5 w-full min-w-0 rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-3 py-3 text-base outline-none" inputMode="decimal" type="number" min={0} value={value} onChange={e=>set(Number(e.target.value))}/></label>}
function Metric({label,value}:{label:string;value:string}){return <div className="min-w-0 rounded-xl bg-[var(--surface-2)] p-3"><p className="truncate text-[9px] uppercase tracking-wide text-[var(--text-muted)]">{label}</p><p className="mt-1 break-words text-xs font-semibold tabular-nums sm:text-sm">{value}</p></div>}
